// <auto-generated />
using System;
using GestionFinanciera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionFinanciera.Migrations
{
    [DbContext(typeof(GestionFinancieraContext))]
    [Migration("20260506065252_m2_integracion_compras")]
    partial class m2_integracion_compras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionFinanciera.Dominio.Arancel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Convenio")
                        .HasColumnType("integer");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioConvenio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id_Convenio");

                    b.ToTable("Arancel");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreAseguradora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeCoberturaBase")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoCobertura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Convenio");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Factura")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id_Factura");

                    b.ToTable("DetalleFactura");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolioExterno1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolioExterno2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Id_Convenio")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoCobertura")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoPaciente")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id_Convenio");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Factura")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Pagado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaBancaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Factura");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.PagoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOrden")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacturaArchivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacturaNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecibidoConforme")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PagoProveedor");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoAsignado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoDisponible")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PresupuestoMensual");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Arancel", b =>
                {
                    b.HasOne("GestionFinanciera.Dominio.Convenio", "Convenio")
                        .WithMany("Aranceles")
                        .HasForeignKey("Id_Convenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.DetalleFactura", b =>
                {
                    b.HasOne("GestionFinanciera.Dominio.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Factura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Factura", b =>
                {
                    b.HasOne("GestionFinanciera.Dominio.Convenio", "Convenio")
                        .WithMany("Facturas")
                        .HasForeignKey("Id_Convenio");

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Pago", b =>
                {
                    b.HasOne("GestionFinanciera.Dominio.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_Factura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Convenio", b =>
                {
                    b.Navigation("Aranceles");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("GestionFinanciera.Dominio.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
